"""Chart data for wenhaochai.com/blogs/per-layer-contribution.html -> assets/data/per-layer-contribution.js (generated;
regenerate, never hand-edit). Same numbers as layer_backbone.py, layer_probe.py and heads_compare.py:
final value = mean of the last 50 logged steps; readout k of the 6-layer 130m model sits at backbone compute
3*(k+1)/6*F_backbone per token (embedding and LM head not counted), the d-layer plain model at d/6 of the baseline's.
Fits L = E + A (C/1e18)^-alpha (curve_fit, E free); the probe series is joined by a monotone PCHIP in log-log, not a fit.
Trajectories: 50-step running means from step 100, thinned to ~120 log-spaced points.
Sources: flops.npz, bbfrozen.npz, depth.json, baselines.json (this directory)."""
import json, sys
from pathlib import Path
import numpy as np
from scipy.interpolate import PchipInterpolator
from scipy.optimize import curve_fit
HERE = Path(__file__).resolve().parent
OUT = Path(sys.argv[1])
TOK, V = 128 * 4096, 128256
D = dict(np.load(HERE / "flops.npz")); Z = np.load(HERE / "bbfrozen.npz")
B = json.load(open(HERE / "baselines.json"))["130m"]; DEPTH = json.load(open(HERE / "depth.json"))
Fb = B["backbone_flops"]
x = [(k + 1) / 6 * Fb for k in range(1, 6)]
law = lambda c, E, A, a: E + A * (c / 1e18) ** (-a)
g = np.geomspace(min(x), max(x), 60)
r = lambda a, n=4: [round(float(v), n) for v in a]
def fit(y):
    p, _ = curve_fit(law, np.array(x), y, p0=(y.min() - 0.3, 0.3, 0.5), bounds=([0, 0, 0], [y.min(), 10, 5]), maxfev=20000)
    return {"E": round(float(p[0]), 4), "A": round(float(p[1]), 4), "alpha": round(float(p[2]), 4), "curve": [[float(f"{c:.4g}"), round(float(law(c, *p)), 4)] for c in g]}
def series(y, kind="fit"):
    y = np.asarray(y, float)
    s = {"x": [float(f"{v:.4g}") for v in x], "y": r(y)}
    if kind == "fit": s.update(fit(y))
    else:
        pch = PchipInterpolator(np.log(x), np.log(y))
        s["curve"] = [[float(f"{c:.4g}"), round(float(np.exp(pch(np.log(c)))), 4)] for c in g]
    return s
plain = [DEPTH[str(d)]["loss"] for d in range(2, 6)] + [B["loss"]]
# trajectories of the separate-heads run, layers 1..5
F = D["130-base/gflops"][-1] * 1e9 / (D["130-base/step"][-1] * TOK) / 3 - 2 * 512 * V
s, ce = D["130-own/step"], D["130-own/ce"]; m = s >= 100
traj = []
for k in range(1, 6):
    xs = (s * TOK * 3 * (k + 1) / 6 * F)[m][49:]
    ys = np.convolve(ce[m, k], np.ones(50) / 50, mode="valid")
    idx = np.unique(np.geomspace(1, len(xs), 120).astype(int) - 1)
    traj.append([[float(f"{xs[i]:.4g}"), round(float(ys[i]), 4)] for i in idx])
data = {
    "note": "generated by build_site_data.py (pls branch, docs/della/pls_archive/blog); do not hand-edit",
    "layers": [1, 2, 3, 4, 5], "depths": [2, 3, 4, 5, 6],
    "separate": series(Z["-pls1-sep/final"][1:]), "shared": series(Z["-pls1/final"][1:]),
    "readonly": series(Z["-pls1-dh/final"][1:]), "plain": series(plain),
    "probe": series(Z["-pls1-sep-bbfrozen/final"][1:], kind="pchip"), "trajSeparate": traj,
}
OUT.write_text("/* Generated by build_site_data.py; regenerate rather than hand-edit. */\nwindow.PLC_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")
print("wrote", OUT, OUT.stat().st_size, "bytes; separate", data["separate"]["y"], "probe", data["probe"]["y"], "plain", data["plain"]["y"])
