"""Chart data for wenhaochai.com/blogs/per-layer-contribution.html -> assets/data/per-layer-contribution.js (generated;
regenerate, never hand-edit). Final training loss (mean of the last 50 logged steps) after layers 2..6 of the 130m model,
numbered from 1, for each setup; the ordinary models have 2..6 layers (the 6-layer one is the baseline). The page draws
differences between these numbers, computed in the page script.
  separate  muonh-qwen3-130m-della4xh100-pls1-sep       every layer trained to predict, a head of its own per layer
  shared    muonh-qwen3-130m-della4xh100-pls1           every layer trained to predict through the output head
  readonly  muonh-qwen3-130m-della4xh100-pls1-dh        as shared, the extra losses leave the head untouched
  probe     muonh-qwen3-130m-della4xh100-pls1-sep-bbfrozen  heads on a detached backbone: a normally trained model, read out
  plain     muonh-qwen3-130m-della4xh100-d{2..5} and the 6-layer baseline
Sources: bbfrozen.npz (fetch_bbfrozen.py), depth.json (fetch_depth.py), baselines.json (fetch_baselines.py)."""
import json, sys
from pathlib import Path
import numpy as np
HERE = Path(__file__).resolve().parent
OUT = Path(sys.argv[1])
Z = np.load(HERE / "bbfrozen.npz")
B = json.load(open(HERE / "baselines.json"))["130m"]
DEPTH = json.load(open(HERE / "depth.json"))
r = lambda a: [round(float(v), 4) for v in a]
data = {
    "note": "generated by build_site_data.py (pls branch, docs/della/pls_archive/blog); do not hand-edit",
    "layers": [2, 3, 4, 5, 6],
    "separate": r(Z["-pls1-sep/final"][1:]), "shared": r(Z["-pls1/final"][1:]), "readonly": r(Z["-pls1-dh/final"][1:]),
    "probe": r(Z["-pls1-sep-bbfrozen/final"][1:]),
    "plain": r([DEPTH[str(d)]["loss"] for d in range(2, 6)] + [B["loss"]]),
}
OUT.write_text("/* Generated by build_site_data.py; regenerate rather than hand-edit. */\nwindow.PLC_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")
print("wrote", OUT, OUT.stat().st_size, "bytes")
for k in ("separate", "shared", "readonly", "probe", "plain"):
    print(f"{k:9s}", data[k])
