"""Chart data for wenhaochai.com/blogs/per-layer-contribution.html -> assets/data/per-layer-contribution.js (generated;
regenerate, never hand-edit). Same numbers as layer_backbone.py, layer_probe.py and heads_compare.py:
final value = mean of the last 50 logged steps; readout k of the 6-layer 130m model sits at backbone compute
3*(k+1)/6*F_backbone per token (embedding and LM head not counted), the d-layer plain model at d/6 of the baseline's.
Fits L = E + A (C/1e18)^-alpha (curve_fit, E free); the probe series is joined by a monotone PCHIP in log-log, not a fit.
Trajectories: 50-step running means from step 100, thinned to ~120 log-spaced points.
Sources: flops.npz, bbfrozen.npz, depth.json, baselines.json (this directory)."""
import json, sys
from pathlib import Path
import numpy as np
from scipy.interpolate import PchipInterpolator
from scipy.optimize import curve_fit
HERE = Path(__file__).resolve().parent
OUT = Path(sys.argv[1])
TOK, V = 128 * 4096, 128256
D = dict(np.load(HERE / "flops.npz")); Z = np.load(HERE / "bbfrozen.npz")
B = json.load(open(HERE / "baselines.json"))["130m"]; DEPTH = json.load(open(HERE / "depth.json"))
Fb = B["backbone_flops"]
x = [(k + 1) / 6 * Fb for k in range(1, 6)]
law = lambda c, E, A, a: E + A * (c / 1e18) ** (-a)
g = np.geomspace(min(x), max(x), 60)
r = lambda a, n=4: [round(float(v), n) for v in a]
def fit(y):
    p, _ = curve_fit(law, np.array(x), y, p0=(y.min() - 0.3, 0.3, 0.5), bounds=([0, 0, 0], [y.min(), 10, 5]), maxfev=20000)
    return {"E": round(float(p[0]), 4), "A": round(float(p[1]), 4), "alpha": round(float(p[2]), 4), "curve": [[float(f"{c:.4g}"), round(float(law(c, *p)), 4)] for c in g]}
def series(y, kind="fit"):
    y = np.asarray(y, float)
    s = {"x": [float(f"{v:.4g}") for v in x], "y": r(y)}
    if kind == "fit": s.update(fit(y))
    else:
        pch = PchipInterpolator(np.log(x), np.log(y))
        s["curve"] = [[float(f"{c:.4g}"), round(float(np.exp(pch(np.log(c)))), 4)] for c in g]
    return s
plain = [DEPTH[str(d)]["loss"] for d in range(2, 6)] + [B["loss"]]
# trajectories of the separate-heads run, layers 1..5
F = D["130-base/gflops"][-1] * 1e9 / (D["130-base/step"][-1] * TOK) / 3 - 2 * 512 * V
s, ce = D["130-own/step"], D["130-own/ce"]; m = s >= 100
traj = []
for k in range(1, 6):
    xs = (s * TOK * 3 * (k + 1) / 6 * F)[m][49:]
    ys = np.convolve(ce[m, k], np.ones(50) / 50, mode="valid")
    idx = np.unique(np.geomspace(1, len(xs), 120).astype(int) - 1)
    traj.append([[float(f"{xs[i]:.4g}"), round(float(ys[i]), 4)] for i in idx])
data = {
    "note": "generated by build_site_data.py (pls branch, docs/della/pls_archive/blog); do not hand-edit",
    "layers": [1, 2, 3, 4, 5], "depths": [2, 3, 4, 5, 6],
    "separate": series(Z["-pls1-sep/final"][1:]), "shared": series(Z["-pls1/final"][1:]),
    "readonly": series(Z["-pls1-dh/final"][1:]), "plain": series(plain),
    "probe": series(Z["-pls1-sep-bbfrozen/final"][1:], kind="pchip"), "trajSeparate": traj,
}
OUT.write_text("/* Generated by build_site_data.py; regenerate rather than hand-edit. */\nwindow.PLC_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")
print("wrote", OUT, OUT.stat().st_size, "bytes; separate", data["separate"]["y"], "probe", data["probe"]["y"], "plain", data["plain"]["y"])

# Thumbnail for the Pretrain Practice landing page: the first chart of the page (separate heads, probe, plain models),
# drawn as an inline SVG in theme colours (CSS variables), no text; written between the thumb markers of the hub page.
if len(sys.argv) > 2:
    hub = Path(sys.argv[2])
    W, Hh, m = 1600, 1000, 90
    keys = [("plain", "var(--ch-ref)"), ("separate", "var(--ch-s1)"), ("probe", "var(--ch-s2)")]
    allx = data["separate"]["x"]; ally = sum((data[k]["y"] for k, _ in keys), [])
    x0, x1 = np.log(min(allx) / 1.6), np.log(max(allx) * 1.25)
    y0, y1 = np.log(0.97 * min(ally)), np.log(1.06 * max(ally))
    X = lambda v: m + (np.log(v) - x0) / (x1 - x0) * (W - 2 * m)
    Y = lambda v: m + (y1 - np.log(v)) / (y1 - y0) * (Hh - 2 * m)
    parts = [f'<svg viewBox="0 0 {W} {Hh}" role="img" aria-label="Per-layer training loss against backbone compute, 130m: separate heads, probe of the baseline, plain models" preserveAspectRatio="xMidYMid meet" style="width:100%;height:100%;display:block">']
    for v in (3.25, 3.5, 3.75, 4, 4.5):
        if y0 <= np.log(v) <= y1:
            parts.append(f'<line x1="{m}" y1="{Y(v):.0f}" x2="{W - m}" y2="{Y(v):.0f}" stroke="var(--ch-grid)" stroke-width="3"/>')
    parts.append(f'<line x1="{m}" y1="{Hh - m}" x2="{W - m}" y2="{Hh - m}" stroke="var(--ch-axis)" stroke-width="3"/>')
    for k, c in keys:
        d = "".join(("L" if i else "M") + f"{X(p[0]):.0f} {Y(p[1]):.0f}" for i, p in enumerate(data[k]["curve"]))
        parts.append(f'<path d="{d}" fill="none" stroke="{c}" stroke-width="9"/>')
        parts += [f'<circle cx="{X(a):.0f}" cy="{Y(b):.0f}" r="17" fill="{c}"/>' for a, b in zip(data[k]["x"], data[k]["y"])]
    parts.append("</svg>")
    s = hub.read_text(); a, b = "<!-- thumb:per-layer-contribution -->", "<!-- /thumb:per-layer-contribution -->"
    i, j = s.index(a) + len(a), s.index(b)
    hub.write_text(s[:i] + "".join(parts) + s[j:])
    print("thumbnail written into", hub)
